version: "3"
services:
  node:
    image: "node:8"
    user: "node"
    working_dir: /app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    command: bash -c "npm install && npm start"